name: Christina Cannone
favicon: null
layout_spectrum: 0.15226101758889854
typography_spectrum: 0.61213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b89675'
    - '#343434'
    - '#6d6248'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.3102714535780251
  saturation: 0.9749009998049587
  rhythmicContrast: 0.5195804645773023
purpose: []
