name: Christina Cannone
favicon: null
layout_spectrum: 0.4085
typography_spectrum: 0.61213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b89675'
    - '#343434'
    - '#6d6248'
    - '#000000'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
