name: Christina Cannone
favicon: null
layout_spectrum: 0.15226101758889854
typography_spectrum: 0.27771306317299604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1524875401519239
  lightness: 0.3102714535780251
  saturation: 0.9749009998049587
  rhythmicContrast: 0.5195804645773023
purpose: []
