name: Christina Cannone
favicon: null
layout_spectrum: 0.15226101758889854
typography_spectrum: 0.27771306317299604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f7fa'
    - '#000024'
    - '#7fa5c0'
    - '#e7434c'
    - '#e9be92'
  brandStrength: 0
  lightness: 0.3102714535780251
  saturation: 0.9749009998049587
  rhythmicContrast: 0.5195804645773023
purpose: []
